# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set -g status-position top
set -g status-justify centre


set -g status-style fg=colour24,bg=colour236
# Set left side status bar length and style
set -g status-left-length 60
set -g status-left-style default

set -g status-left "#[bg=colour34,fg=black]#{?client_prefix,[*],[ ]} [#S] #[fg=colour34,bg=colour236] "

# Set right side status bar length and style
set -g status-right-length 140
set -g status-right-style default

# Display the hostname
set -g status-right "#[fg=colour34,bg=colour236]#[fg=black,bg=colour34] \"#H\" "

# Display the date
set -ag status-right "[%d-%m-%Y]"

# Display the time
set -ag status-right "[%H:%M]"

# Set the inactive window color and style
set -g window-status-style fg=colour244,bg=default
set -g window-status-format ' #I: #W '

# Set the active window color and style
# set -g window-status-current-style fg=black,bg=colour34
set -g window-status-current-format '#[fg=colour34,bg=colour236]#[fg=black,bg=colour34]#I:[#W]#[fg=colour34,bg=colour236]'

# Colors for pane borders(default)
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=white,bg=black

# Active pane normal, other shaded out
setw -g window-style fg=colour240,bg=colour235
setw -g window-active-style fg=white,bg=black

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
